// Mock data para desarrollo y testing del módulo SLA Manager
// Este archivo simula las respuestas del backend

export const mockAlertas = [
  {
    idAlerta: 105,
    tipoAlerta: 'VENCIMIENTO_PROXIMO',
    nivel: 'WARNING',
    mensaje: 'Faltan 2 día(s) para el umbral',
    estado: 'NUEVA',
    fechaCreacion: '2025-11-21T10:00:00',
    solicitud: {
      idSolicitud: 'SOL-102',
      numDiasSla: 35,
      diasTranscurridos: 33,
      personal: { cargo: 'Developer' },
      configSla: { codigoSla: 'SLA1' },
    },
  },
  {
    idAlerta: 106,
    tipoAlerta: 'SLA_EXCEDIDO',
    nivel: 'CRITICAL',
    mensaje: 'SLA excedido en 3 día(s)',
    estado: 'NUEVA',
    fechaCreacion: '2025-11-21T09:30:00',
    solicitud: {
      idSolicitud: 'SOL-098',
      numDiasSla: 20,
      diasTranscurridos: 23,
      personal: { cargo: 'Senior Developer' },
      configSla: { codigoSla: 'SLA2' },
    },
  },
  {
    idAlerta: 107,
    tipoAlerta: 'VENCIMIENTO_PROXIMO',
    nivel: 'WARNING',
    mensaje: 'Faltan 5 día(s) para el umbral',
    estado: 'LEIDA',
    fechaCreacion: '2025-11-20T16:45:00',
    solicitud: {
      idSolicitud: 'SOL-110',
      numDiasSla: 30,
      diasTranscurridos: 25,
      personal: { cargo: 'QA Engineer' },
      configSla: { codigoSla: 'SLA1' },
    },
  },
  {
    idAlerta: 108,
    tipoAlerta: 'SLA_EXCEDIDO',
    nivel: 'CRITICAL',
    mensaje: 'SLA excedido en 7 día(s)',
    estado: 'NUEVA',
    fechaCreacion: '2025-11-20T14:20:00',
    solicitud: {
      idSolicitud: 'SOL-085',
      numDiasSla: 15,
      diasTranscurridos: 22,
      personal: { cargo: 'Tech Lead' },
      configSla: { codigoSla: 'SLA2' },
    },
  },
  {
    idAlerta: 109,
    tipoAlerta: 'VENCIMIENTO_PROXIMO',
    nivel: 'WARNING',
    mensaje: 'Faltan 1 día(s) para el umbral',
    estado: 'NUEVA',
    fechaCreacion: '2025-11-21T11:15:00',
    solicitud: {
      idSolicitud: 'SOL-115',
      numDiasSla: 40,
      diasTranscurridos: 39,
      personal: { cargo: 'Project Manager' },
      configSla: { codigoSla: 'SLA1' },
    },
  },
  {
    idAlerta: 110,
    tipoAlerta: 'VENCIMIENTO_PROXIMO',
    nivel: 'WARNING',
    mensaje: 'Faltan 3 día(s) para el umbral',
    estado: 'LEIDA',
    fechaCreacion: '2025-11-19T08:00:00',
    solicitud: {
      idSolicitud: 'SOL-095',
      numDiasSla: 25,
      diasTranscurridos: 22,
      personal: { cargo: 'Business Analyst' },
      configSla: { codigoSla: 'SLA2' },
    },
  },
  {
    idAlerta: 111,
    tipoAlerta: 'SLA_EXCEDIDO',
    nivel: 'CRITICAL',
    mensaje: 'SLA excedido en 1 día(s)',
    estado: 'NUEVA',
    fechaCreacion: '2025-11-21T07:30:00',
    solicitud: {
      idSolicitud: 'SOL-120',
      numDiasSla: 10,
      diasTranscurridos: 11,
      personal: { cargo: 'UX Designer' },
      configSla: { codigoSla: 'SLA1' },
    },
  },
  {
    idAlerta: 112,
    tipoAlerta: 'VENCIMIENTO_PROXIMO',
    nivel: 'WARNING',
    mensaje: 'Faltan 4 día(s) para el umbral',
    estado: 'NUEVA',
    fechaCreacion: '2025-11-20T12:00:00',
    solicitud: {
      idSolicitud: 'SOL-105',
      numDiasSla: 28,
      diasTranscurridos: 24,
      personal: { cargo: 'DevOps Engineer' },
      configSla: { codigoSla: 'SLA2' },
    },
  },
]
